### ISSUE TITLE
About your approval for documentation rendering

### ISSUE THREAD

**Issue by sypets** [geraldloss/glcrossword#1]
see [Slack](https://typo3.slack.com/archives/C028JEPJL/p1574734920116800)

You successfully added a Webhook and a request for approval has been sent. (see https://intercept.typo3.com/admin/docs/deployments).

-----

The approval process is in place to make sure, that the documentation rendering request is legitimate, meaning the request comes from the person(s) owning that extension. We can usually do a quick check, for example for checking if extensions (that are already approved) with the same vendor come from the same GitHub user. This gives us a hint that everything is ok. Another possibility is to check if the extension is listed on extensions.typo3.org and if the link "Code Insights" points to the same repository the documentation rendering request is coming from.

So, please do the following:

For your extension `loss/glcrossword` , add a link (on extensions.typo3.org) to the code repository on GitHub. For example, for `loss/glcrossword` add a link to https://github.com/geraldloss/glcrossword. This has the additional advantage that it shows people on extensions.typo3.org where to find your code and where they might contribute.

You can look at other extensions to see how it looks: https://extensions.typo3.org/extension/gpsnose/ (see link "Code Insights").

Please let me know when you have done this. I can then approve and your extension documentation will be rendered. For further extensions (with the same vendor and same GitHub user account), this will not be necessary.

How can you add the link?

Go to extensions.typo3.org,  log in and click on "My extensions".

**Comment by geraldloss** [comment]
Hello Sybille,

I have add a Link from my Extension to the GitHub folder. You can activate now my Webhook now.
It is possible to communicate over Slack? Could you please invite me to your Workspace typo3.slack.com?

Thank you and best regards
Gerald

**Comment by sypets** [comment]
Slack: 

1. You must have an account on typo3.org : https://my.typo3.org
2. Once signed up (and logged in), you should be able to add the Slack workspace, click on "About my.typo3.org"
3. Once you have logged in to https://typo3.slack.com, you can join the #typo3-documentation channel (this is public within the Slack workspace)

See https://my.typo3.org/about-mytypo3org/slack

**Comment by sypets** [comment]
Your extension has been approved, but the rendering failed, see https://intercept.typo3.com/admin/docs/deployments

Filter for glcrossword (in left text field): 

![glcrossword](https://user-images.githubusercontent.com/13206455/69726311-8ec32200-1120-11ea-9e25-3f2aa0d2be23.png)

When you click on the link in the column, last rendered, you can see the error logs. 

https://bamboo.typo3.com/browse/CORE-DR-JOB1-9190/log


```
==================================================
--
26-Nov-2019 10:52:10 | 16-Convert-and-fix-and-check/run_05-Learn-from-settings-cfg.py
26-Nov-2019 10:52:10 | Traceback (most recent call last):
26-Nov-2019 10:52:10 | File "/ALL/Toolchains/RenderDocumentation/16-Convert-and-fix-and-check/run_05-Learn-from-settings-cfg.py", line 95, in <module>
26-Nov-2019 10:52:10 | config.readfp(codecs.open(settingscfg_file, 'r', 'utf-8'))
26-Nov-2019 10:52:10 | File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
26-Nov-2019 10:52:10 | self._read(fp, filename)
26-Nov-2019 10:52:10 | File "/usr/lib/python2.7/ConfigParser.py", line 479, in _read
26-Nov-2019 10:52:10 | line = fp.readline()
26-Nov-2019 10:52:10 | File "/ALL/userhome/.local/share/virtualenvs/venv-y0waPz_e/lib/python2.7/codecs.py", line 692, in readline
26-Nov-2019 10:52:10 | return self.reader.readline(size)
26-Nov-2019 10:52:10 | File "/ALL/userhome/.local/share/virtualenvs/venv-y0waPz_e/lib/python2.7/codecs.py", line 547, in readline
26-Nov-2019 10:52:10 | data = self.read(readsize, firstline=True)
26-Nov-2019 10:52:10 | File "/ALL/userhome/.local/share/virtualenvs/venv-y0waPz_e/lib/python2.7/codecs.py", line 494, in read
26-Nov-2019 10:52:10 | newchars, decodedbytes = self.decode(data, self.errors)
26-Nov-2019 10:52:10 | UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 4: invalid continuation byte
26-Nov-2019 10:52:10 | exitcode:   1            35 ms

```

There appears to be a problem with Settings.cfg. I will clone your extension and try to render locally to see if I can reproduce and fix this.

**Comment by sypets** [comment]
There is an encoding problem in Documentation/Settings.cfg

* As a general rule, please make sure all files are saved as utf-8.
* You can test the rendering locally by using the Docker container: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Quickstart.html#render-documenation-with-docker

When I manually edit Documentation/Settings.cfg, it renders fine. I will push a pull request.
